#!/bin/sh

# main
IMG=mkdocs
TAG=latest

if ! [ -f ./config ]; then
  echo "No such ./config"
  exit 1
fi

if ! [ -f ./priv.key ]; then
  echo "No such ./priv.key"
  exit 1
fi

case "$1" in 
  build|gh-deploy)
    ;;
  *)
    echo "Not support command. Only 'build' or 'gh-deploy'"
    exit 1
    ;;
esac

CNT=`docker images "${IMG}" -q | wc -l`
if [ ${CNT} -eq 0 ]; then
  if ! [ -f ./Dockerfile ]; then
    echo "No such ./Dockerfile"
    exit 1
  fi
  docker build -u ${USER} -t ${IMG}:${TAG} .
fi

docker run --rm -it -u ${USER} -v ${PWD}:/home/${USER}/docs ${IMG}:${TAG} mkdocs "$1"

