#!/bin/sh

# main
IMG=mkdocs
TAG=latest

if ! [ -f ./config ]; then
  echo "No such ./config"
  exit 1
fi

if ! [ -f ./priv.key ]; then
  echo "No such ./priv.key"
  exit 1
fi

case "$1" in 
  --help|serve|build|gh-deploy)
    CLI=mkdocs
    ;;
  *)
    CLI=
#    echo "Not support command. Only 'build' or 'gh-deploy'"
#    exit 1
    ;;
esac

CNT=`docker images "${IMG}" -q | wc -l`
if [ ${CNT} -eq 0 ]; then
  if ! [ -f ./Dockerfile ]; then
    echo "No such ./Dockerfile"
    exit 1
  fi
  docker build --build-arg USER=${USER} -t ${IMG}:${TAG} .
fi

PORT=8000
docker run --rm -it -u ${USER} \
	-p ${PORT}:8000 \
	-v ${PWD}:/home/${USER}/docs \
	${IMG}:${TAG} \
	${CLI} "$@"

